const products = [
  { name: "Sunday Lasagna", category: "Ready to bake · Serves 4", price: "$48", image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=900&q=85" },
  { name: "Handmade Tagliatelle", category: "Fresh pasta · 500g", price: "$18", image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85" },
  { name: "Luma Tomato Sugo", category: "House pantry · 16oz", price: "$14", image: "https://images.unsplash.com/photo-1598866594230-a7c12756260f?auto=format&fit=crop&w=900&q=85" },
  { name: "Dinner for Two", category: "Chef's box · Three courses", price: "$72", image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=900&q=85" },
];

export default function Home() {
  return (
    <main>
      <div className="announcement">Order by 3 PM for same-day pickup</div>
      <nav className="nav" aria-label="Main navigation"><a className="brand" href="#top">LUMA MARKET<span>.</span></a><div className="navlinks"><a href="#shop">Order</a><a href="#story">Our kitchen</a><a href="#visit">Visit</a></div><a className="cart" href="mailto:orders@lumamarket.com?subject=Pickup%20order">Order <span>↗</span></a></nav>
      <section className="hero" id="top"><div className="hero-copy"><p className="kicker">The Luma kitchen, to go</p><h1>Made here.<br /><em>Finished at home.</em></h1><p className="lede">Fresh pasta, prepared dinners, and the pantry staples we use every night in our restaurant.</p><a className="button dark" href="#shop">Shop the menu <span>↗</span></a></div><div className="hero-image" style={{ backgroundImage: "linear-gradient(0deg, rgba(20,22,18,.38), transparent 40%), url('https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1600&q=88')" }} role="img" aria-label="Fresh handmade pasta in the Luma kitchen"><span>Fresh from our kitchen · Tuesday–Sunday</span></div></section>
      <section className="intro" id="story"><p className="section-label">From our restaurant</p><h2>Dinner, almost done.</h2><div><p>We prep it the same way we do for service: seasonal ingredients, slow sauces, and pasta rolled by hand. You take it home and make it yours.</p><a href="#shop">See what’s cooking →</a></div></section>
      <section className="shop" id="shop"><div className="section-heading"><div><p className="section-label">This week</p><h2>From the market</h2></div><a href="mailto:orders@lumamarket.com?subject=Weekly%20menu">Ask about today’s menu ↗</a></div><div className="product-grid">{products.map((product) => (<article className="product" key={product.name}><a className="product-image" href={`mailto:orders@lumamarket.com?subject=${encodeURIComponent(product.name)}`} style={{ backgroundImage: `url(${product.image})` }} aria-label={`Order ${product.name}`}><span>Order for pickup</span></a><div className="product-info"><div><p>{product.category}</p><h3>{product.name}</h3></div><strong>{product.price}</strong></div></article>))}</div></section>
      <section className="feature"><div className="feature-image" style={{ backgroundImage: "url('https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1500&q=85')" }} role="img" aria-label="Chef preparing food in the restaurant kitchen"></div><div className="feature-copy"><p className="section-label">At the restaurant</p><h2>Stay for<br />dinner.</h2><p>Luma is a neighborhood Italian dining room built around handmade pasta, open-fire cooking, and the kind of hospitality that keeps the table warm.</p><a className="button light" href="mailto:hello@lumamarket.com?subject=Table%20reservation">Reserve a table <span>↗</span></a></div></section>
      <section className="newsletter"><p className="section-label">The weekly menu</p><h2>Know what’s cooking.</h2><p>New market dishes, seasonal pantry drops, and restaurant news—sent once a week.</p><form action="mailto:hello@lumamarket.com" method="post"><label className="sr-only" htmlFor="email">Email address</label><input id="email" type="email" name="email" placeholder="Your email address" required /><button type="submit">Join the list ↗</button></form></section>
      <footer id="visit"><a className="brand footer-brand" href="#top">LUMA MARKET<span>.</span></a><div><p>Market hours</p><a href="#shop">Tue–Sun, 11 AM–7 PM</a><a href="#shop">Pickup at the bar</a></div><div><p>Find us</p><a href="https://maps.google.com/?q=284+Fremont+Street+Las+Vegas+NV" target="_blank" rel="noreferrer">284 Fremont Street<br />Las Vegas, Nevada</a><a href="mailto:hello@lumamarket.com">hello@lumamarket.com</a></div><p className="fineprint">© 2026 Luma Market<br />Made with care in Las Vegas.</p></footer>
    </main>
  );
}
